# Data Observation and Curation

## Data Management

Store all of your research data in the `data` subdirectories. It is recommended that raw data not be altered once downloaded or collected. Maintaining a separate raw data file facilitates reproducibility be preserving a common point of analytical origin. It is similarly recommended that whenever possible data processing, transformation, or manipulation be completed with code as this practice facilitates re-analysis and reduces opportunities of confusion.

Complete the [data_metadata.csv](data_metadata.csv) file indexing each **raw** and **derived** data file, including the fields:

- `path`: the path to the data folder, likely one of: `raw\private`, `raw\public`, `derived\private` or `derived\public`
- `name`: the file name, including extension
- `metadata`: list of metadata files for this data source, stored in the `data\metadata` folder. These may include ISO-191** or FGDC standard `XML` files, data dictionaries, licenses or attributions, user guides, webpage printouts, etc.
- `status`: which may be `included` for data included in the repository or `create` or `acquire` for data that must created or acquired, `derived` for data that will be generated by code from other data files, `simulated` for data that replaces the true research data with a simulated data due to confidentiality or legal constraints, and `unavailable` for data that cannot be shared or reproduced in any way.
- `description`: *very* brief description of the dataset.

Researchers are **strongly encouraged** to include additional metadata in the `metadata` folder.
Further information about the procedures used to create data with 'status = derive' should be maintained in the [procedure_metadata.csv](../procedure/procedure_metadata.csv).

See more about metadata in the engaging with data section of the previous chapter.

## Collect preliminary data

- metadata!
- code/scripts for data acquisition
- directory structure for data
  - scratch (not tracked)
  - raw / public
  - raw / private (not tracked)
  - derived / public
  - derived / private (not tracked)
- file size limits for GitHub / GitLab

| Processing | Access | -- |
| :--: | :--: | :--: |
|  | Private | Public |
| Raw | RPri | RPub |
| Derived | DPri | DPub

### Raw Private Data

Store raw data in this folder as it is collected or downloaded if the data cannot be publicly redistributed. For example, data versioning and sharing my be restricted because of large file sizes, licensing, ethics, privacy, or confidentiality. Best practices are to include code to automate the process of downloading or simulating raw private data in the first step of the methods, or to include instructions here for accessing any private or restricted-access data.



*This folder is ignored by Git versioning* with the exception of this `readme.md` file by the following lines in `.gitignore`

```gitignore
# Ignore contents of private folder, with the exception of its readme file
private/**
!private/readme.md
```

### Caution: Dealing with large files

- GitHub will not store files larger than 100mb
- These should be placed in `private` directories so that they are not tracked by Git or uploaded to GitHub
- OSF and Figshare both allow for larger file storage options, so you may store large files on those services and write code for downloading those files to private directories as the analysis runs. Significant data sources could be registered with their own DOI links.

Git and GitHub are not designed to track or store large files over 100 mb.

- If you have accidentally attempted to commit changes with large files, do this...
- Recommend saving large files on OSF or Figshare and writing scripts to pull them into the private folder

### Caution: Dealing with large files

- GitHub will not store files larger than 100mb
- These should be placed in `private` directories so that they are not tracked by Git or uploaded to GitHub
- OSF and Figshare both allow for larger file storage options, so you may store large files on those services and write code for downloading those files to private directories as the analysis runs. Significant data sources could be registered with their own DOI links.


## Accommodate the unexpected!

You will likely encounter unexpected challenges and the need to change your original, pre-analysis registration plan.
This is normal: just be diligent about updating your pre-analysis plan, committing changes
